import {
  StudentProfile,
  IndustryProfile,
  AcademicianProfile,
  InstitutionAdminProfile,
  SkillMaster,
  SkillAssessmentQuestion,
  JobOpportunity,
  JobApplication,
  RAGDocument,
} from '../types';

export const DEMO_INSTITUTIONS = [
  {
    id: 'inst_iitb',
    name: 'Indian Institute of Technology, Bombay (IIT Bombay)',
    code: 'IITB',
    location: 'Mumbai, Maharashtra',
    website: 'https://www.iitb.ac.in',
    totalStudents: 12500,
  },
  {
    id: 'inst_nitt',
    name: 'National Institute of Technology, Tiruchirappalli (NIT Trichy)',
    code: 'NITT',
    location: 'Tiruchirappalli, Tamil Nadu',
    website: 'https://www.nitt.edu',
    totalStudents: 6800,
  },
  {
    id: 'inst_bits',
    name: 'Birla Institute of Technology and Science, Pilani (BITS Pilani)',
    code: 'BITS',
    location: 'Pilani, Rajasthan',
    website: 'https://www.bits-pilani.ac.in',
    totalStudents: 9400,
  },
];

export const DEMO_SKILLS: SkillMaster[] = [
  { id: 'sk_js', name: 'JavaScript', category: 'technical', description: 'ES6+, Async/Await, Closures, Event Loop', popularDemandScore: 95 },
  { id: 'sk_react', name: 'React', category: 'technical', description: 'JSX, Hooks, Context API, Redux/Zustand', popularDemandScore: 92 },
  { id: 'sk_nextjs', name: 'Next.js', category: 'technical', description: 'App Router, SSR, SSG, Server Actions', popularDemandScore: 89 },
  { id: 'sk_nodejs', name: 'Node.js', category: 'technical', description: 'Event Driven I/O, Express, Streams', popularDemandScore: 90 },
  { id: 'sk_express', name: 'Express.js', category: 'technical', description: 'REST APIs, Middleware, Routing', popularDemandScore: 85 },
  { id: 'sk_ts', name: 'TypeScript', category: 'technical', description: 'Static Typing, Interfaces, Generics', popularDemandScore: 93 },
  { id: 'sk_python', name: 'Python', category: 'technical', description: 'Data Structures, Scripting, NumPy, Pandas', popularDemandScore: 96 },
  { id: 'sk_java', name: 'Java', category: 'technical', description: 'OOP, Spring Boot, Multithreading', popularDemandScore: 88 },
  { id: 'sk_sql', name: 'SQL', category: 'technical', description: 'Queries, Joins, Indexing, Transactions', popularDemandScore: 94 },
  { id: 'sk_mongo', name: 'MongoDB', category: 'technical', description: 'Document DB, Aggregations, Mongoose', popularDemandScore: 84 },
  { id: 'sk_postgres', name: 'PostgreSQL', category: 'technical', description: 'Relational DB, JSONB, Performance Tuning', popularDemandScore: 89 },
  { id: 'sk_docker', name: 'Docker', category: 'technical', description: 'Containerization, Dockerfile, Docker Compose', popularDemandScore: 87 },
  { id: 'sk_k8s', name: 'Kubernetes', category: 'technical', description: 'Container Orchestration, Deployments, Services', popularDemandScore: 81 },
  { id: 'sk_aws', name: 'AWS Cloud', category: 'technical', description: 'EC2, S3, Lambda, DynamoDB, IAM', popularDemandScore: 91 },
  { id: 'sk_ml', name: 'Machine Learning', category: 'technical', description: 'Scikit-learn, Regression, Classification', popularDemandScore: 93 },
  { id: 'sk_dl', name: 'Deep Learning', category: 'technical', description: 'PyTorch, TensorFlow, CNNs, Transformers', popularDemandScore: 88 },
  { id: 'sk_nlp', name: 'NLP & LLMs', category: 'technical', description: 'LangChain, Vector DBs, RAG, Fine-tuning', popularDemandScore: 95 },
  { id: 'sk_cyber', name: 'Cybersecurity', category: 'technical', description: 'Penetration Testing, OWASP Top 10, Network Security', popularDemandScore: 86 },
  { id: 'sk_sysdesign', name: 'System Design', category: 'technical', description: 'Scalability, Load Balancing, Caching, Microservices', popularDemandScore: 90 },
  { id: 'sk_git', name: 'Git & GitHub', category: 'technical', description: 'Version Control, Branching, PRs, CI/CD Actions', popularDemandScore: 97 },
  { id: 'sk_comm', name: 'Communication', category: 'soft', description: 'Verbal & Written expression, Presentation skills', popularDemandScore: 95 },
  { id: 'sk_probsolv', name: 'Problem Solving', category: 'soft', description: 'Analytical thinking, Algorithmic reasoning', popularDemandScore: 98 },
  { id: 'sk_team', name: 'Teamwork', category: 'soft', description: 'Cross-functional collaboration, Empathy', popularDemandScore: 90 },
  { id: 'sk_lead', name: 'Leadership', category: 'soft', description: 'Project management, Decision making, Ownership', popularDemandScore: 85 },
  { id: 'sk_time', name: 'Time Management', category: 'soft', description: 'Prioritization, Task scheduling, Deadlines', popularDemandScore: 88 },
];

export const DEMO_ASSESSMENT_QUESTIONS: SkillAssessmentQuestion[] = [
  // JavaScript
  {
    id: 'q_js_1',
    skillId: 'sk_js',
    skillName: 'JavaScript',
    category: 'technical',
    question: 'What is the output of `console.log(typeof typeof 1)` in JavaScript?',
    options: ['"number"', '"string"', '"undefined"', '"object"'],
    correctOptionIndex: 1,
    explanation: '`typeof 1` evaluates to string `"number"`. Then `typeof "number"` evaluates to `"string"`.',
    difficulty: 'easy',
  },
  {
    id: 'q_js_2',
    skillId: 'sk_js',
    skillName: 'JavaScript',
    category: 'technical',
    question: 'Which method creates a new array with all elements that pass the test implemented by the provided function?',
    options: ['map()', 'filter()', 'reduce()', 'forEach()'],
    correctOptionIndex: 1,
    explanation: '`filter()` creates a shallow copy of a portion of a given array, filtered down to just the elements that pass the test.',
    difficulty: 'easy',
  },
  {
    id: 'q_js_3',
    skillId: 'sk_js',
    skillName: 'JavaScript',
    category: 'technical',
    question: 'What is a closure in JavaScript?',
    options: [
      'A function combined with references to its lexical environment',
      'A method to close browser tabs programmatically',
      'A private class variable syntax',
      'An error handling mechanism in async functions',
    ],
    correctOptionIndex: 0,
    explanation: 'A closure is the combination of a function bundled together with references to its surrounding state (lexical environment).',
    difficulty: 'medium',
  },
  // React
  {
    id: 'q_react_1',
    skillId: 'sk_react',
    skillName: 'React',
    category: 'technical',
    question: 'What is the main purpose of React `useCallback` hook?',
    options: [
      'To fetch data asynchronously from APIs',
      'To memoize callback functions between re-renders to prevent unnecessary child re-renders',
      'To trigger side effects after component updates',
      'To store mutable values that do not re-render the UI',
    ],
    correctOptionIndex: 1,
    explanation: '`useCallback` caches a function definition between renders when passed down to optimized child components.',
    difficulty: 'medium',
  },
  {
    id: 'q_react_2',
    skillId: 'sk_react',
    skillName: 'React',
    category: 'technical',
    question: 'In React 18/19, what does Server Components allow developers to do?',
    options: [
      'Run React components exclusively on the client browser',
      'Render components on the server without sending JavaScript bundle for those components to the client',
      'Bypass all state management libraries completely',
      'Automatically compile CSS files into inline styles',
    ],
    correctOptionIndex: 1,
    explanation: 'React Server Components execute only on the server, reducing bundle size and enabling direct database access.',
    difficulty: 'hard',
  },
  // Python & Data / AI
  {
    id: 'q_python_1',
    skillId: 'sk_python',
    skillName: 'Python',
    category: 'technical',
    question: 'Which list comprehension syntax correctly filters even numbers from a list `nums`?',
    options: [
      '[x for x in nums if x % 2 == 0]',
      '[x if x % 2 == 0 for x in nums]',
      'filter(x % 2 == 0, nums)',
      '[for x in nums if x % 2 == 0 select x]',
    ],
    correctOptionIndex: 0,
    explanation: 'The standard list comprehension syntax with an `if` clause is `[expression for item in iterable if condition]`.',
    difficulty: 'easy',
  },
  {
    id: 'q_nlp_1',
    skillId: 'sk_nlp',
    skillName: 'NLP & LLMs',
    category: 'technical',
    question: 'In Retrieval-Augmented Generation (RAG), what is the primary role of Vector Embeddings?',
    options: [
      'To encrypt user prompts before transmitting over HTTPS',
      'To convert text chunks into high-dimensional numerical vectors for semantic similarity search',
      'To speed up SQL table joins in PostgreSQL',
      'To replace neural network weight matrices during model training',
    ],
    correctOptionIndex: 1,
    explanation: 'Embeddings capture semantic meanings of text as dense vectors, allowing similarity search (e.g. cosine distance) in vector databases like Pinecone.',
    difficulty: 'medium',
  },
  // Soft Skills
  {
    id: 'q_comm_1',
    skillId: 'sk_comm',
    skillName: 'Communication',
    category: 'soft',
    question: 'When presenting a complex technical solution to non-technical stakeholders, what is the best strategy?',
    options: [
      'Use maximum low-level architectural jargon to sound authoritative',
      'Focus on business impact, high-level user benefits, and clear visual analogies',
      'Skip the presentation entirely and send raw code links',
      'Rush through technical diagrams without taking questions',
    ],
    correctOptionIndex: 1,
    explanation: 'Effective communication requires tailoring the narrative to the audience’s domain and highlighting business value.',
    difficulty: 'easy',
  },
  {
    id: 'q_probsolv_1',
    skillId: 'sk_probsolv',
    skillName: 'Problem Solving',
    category: 'soft',
    question: 'When encountering a critical production bug with zero stack trace, what should be your immediate structured approach?',
    options: [
      'Randomly edit code until it stops crashing',
      'Reproduce the issue locally, isolate recent commit diffs, inspect logs, and form testable hypotheses',
      'Blame the infrastructure team immediately',
      'Rewrite the entire application from scratch in a new framework',
    ],
    correctOptionIndex: 1,
    explanation: 'Structured root cause analysis relies on reproduction, differential isolation, and logging empirical evidence.',
    difficulty: 'medium',
  },
];

export const DEMO_STUDENTS: StudentProfile[] = [
  {
    uid: 'std_aarav',
    email: 'aarav.sharma@iitb.ac.in',
    name: 'Aarav Sharma',
    role: 'student',
    institutionId: 'inst_iitb',
    institutionName: 'IIT Bombay',
    department: 'Computer Science and Engineering',
    degree: 'B.Tech',
    graduationYear: 2026,
    careerGoal: 'Full Stack Developer',
    bio: 'Passionate full-stack developer with experience in React, Node.js, and cloud architectures. Winner of Smart India Hackathon internal rounds.',
    phone: '+91 98765 43210',
    location: 'Mumbai, Maharashtra',
    githubUrl: 'https://github.com/aaravsharma-dev',
    linkedinUrl: 'https://linkedin.com/in/aaravsharma-iitb',
    portfolioUrl: 'https://aaravsharma.dev',
    readinessScore: 88,
    employabilityScore: 92,
    technicalScore: 90,
    softSkillScore: 85,
    createdAt: '2025-08-10T10:00:00Z',
    updatedAt: '2026-09-01T15:30:00Z',
    skills: [
      { skillId: 'sk_js', skillName: 'JavaScript', category: 'technical', proficiencyLevel: 'expert', verificationLevel: 'assessment_verified', score: 92 },
      { skillId: 'sk_react', skillName: 'React', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'project_verified', score: 88 },
      { skillId: 'sk_nextjs', skillName: 'Next.js', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'project_verified', score: 85 },
      { skillId: 'sk_nodejs', skillName: 'Node.js', category: 'technical', proficiencyLevel: 'intermediate', verificationLevel: 'assessment_verified', score: 75 },
      { skillId: 'sk_express', skillName: 'Express.js', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'assessment_verified', score: 82 },
      { skillId: 'sk_ts', skillName: 'TypeScript', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'project_verified', score: 86 },
      { skillId: 'sk_sql', skillName: 'SQL', category: 'technical', proficiencyLevel: 'intermediate', verificationLevel: 'assessment_verified', score: 78 },
      { skillId: 'sk_comm', skillName: 'Communication', category: 'soft', proficiencyLevel: 'advanced', verificationLevel: 'self_declared', score: 85 },
      { skillId: 'sk_probsolv', skillName: 'Problem Solving', category: 'soft', proficiencyLevel: 'expert', verificationLevel: 'assessment_verified', score: 94 },
    ],
    projects: [
      {
        id: 'proj_1',
        title: 'SkillBridge AI - Academia Industry Portal',
        description: 'Next.js 15 & Node.js AI-driven skill gap mapping platform with Pinecone RAG chatbot.',
        role: 'Lead Full Stack Architect',
        techStack: ['Next.js', 'React', 'Node.js', 'Express', 'Pinecone', 'Gemini AI'],
        githubUrl: 'https://github.com/aaravsharma-dev/skillbridge-ai',
        verified: true,
      },
      {
        id: 'proj_2',
        title: 'EduSphere Realtime Learning Platform',
        description: 'Collaborative live quiz and interactive whiteboard system built with Socket.io and Redis.',
        role: 'Frontend Developer',
        techStack: ['React', 'TypeScript', 'Socket.io', 'Tailwind CSS'],
        githubUrl: 'https://github.com/aaravsharma-dev/edusphere',
        verified: true,
      },
    ],
    certifications: [
      {
        id: 'cert_1',
        title: 'Meta Certified Front-End Developer',
        issuingOrganization: 'Meta via Coursera',
        issueDate: '2025-06-15',
        skillsCovered: ['JavaScript', 'React', 'CSS', 'Git'],
        verified: true,
      },
      {
        id: 'cert_2',
        title: 'AWS Certified Cloud Practitioner',
        issuingOrganization: 'Amazon Web Services',
        issueDate: '2025-11-20',
        skillsCovered: ['AWS Cloud', 'EC2', 'S3', 'IAM'],
        verified: true,
      },
    ],
    internships: [
      {
        id: 'exp_1',
        companyName: 'TechCorp India',
        role: 'Full Stack Engineering Intern',
        duration: '3 Months (May 2025 - Aug 2025)',
        description: 'Developed internal microservices using Node.js & React, improving API response times by 35%.',
      },
    ],
  },
  {
    uid: 'std_priya',
    email: 'priya.patel@nitt.edu',
    name: 'Priya Patel',
    role: 'student',
    institutionId: 'inst_nitt',
    institutionName: 'NIT Trichy',
    department: 'Artificial Intelligence & Data Science',
    degree: 'B.Tech',
    graduationYear: 2026,
    careerGoal: 'AI/ML Engineer',
    bio: 'ML practitioner specializing in NLP, Retrieval-Augmented Generation, and PyTorch model optimization.',
    readinessScore: 84,
    employabilityScore: 89,
    technicalScore: 92,
    softSkillScore: 80,
    createdAt: '2025-09-01T12:00:00Z',
    updatedAt: '2026-09-01T16:00:00Z',
    skills: [
      { skillId: 'sk_python', skillName: 'Python', category: 'technical', proficiencyLevel: 'expert', verificationLevel: 'assessment_verified', score: 95 },
      { skillId: 'sk_ml', skillName: 'Machine Learning', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'project_verified', score: 90 },
      { skillId: 'sk_dl', skillName: 'Deep Learning', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'project_verified', score: 86 },
      { skillId: 'sk_nlp', skillName: 'NLP & LLMs', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'project_verified', score: 88 },
      { skillId: 'sk_sql', skillName: 'SQL', category: 'technical', proficiencyLevel: 'intermediate', verificationLevel: 'assessment_verified', score: 80 },
    ],
    projects: [
      {
        id: 'proj_3',
        title: 'MedRAG — Medical Document QA Bot',
        description: 'Pinecone and Gemini 1.5 powered clinical query assistant with zero hallucination enforcement.',
        role: 'AI Researcher & Engineer',
        techStack: ['Python', 'Pinecone', 'Gemini AI', 'FastAPI', 'PyTorch'],
        githubUrl: 'https://github.com/priyapatel/medrag',
        verified: true,
      },
    ],
    certifications: [
      {
        id: 'cert_3',
        title: 'Deep Learning Specialization',
        issuingOrganization: 'DeepLearning.AI',
        issueDate: '2025-05-10',
        skillsCovered: ['Python', 'Deep Learning', 'PyTorch', 'CNNs'],
        verified: true,
      },
    ],
    internships: [
      {
        id: 'exp_2',
        companyName: 'Innovate AI Labs',
        role: 'AI Research Intern',
        duration: '4 Months (Jan 2026 - Apr 2026)',
        description: 'Fine-tuned LLM embeddings for domain-specific document search in finance.',
      },
    ],
  },
  {
    uid: 'std_rohan',
    email: 'rohan.mehta@bits-pilani.ac.in',
    name: 'Rohan Mehta',
    role: 'student',
    institutionId: 'inst_bits',
    institutionName: 'BITS Pilani',
    department: 'Electronics & Communication',
    degree: 'B.E.',
    graduationYear: 2026,
    careerGoal: 'Cloud Engineer',
    bio: 'DevOps & Cloud Systems enthusiast with hands-on experience in AWS, Kubernetes, Terraform, and CI/CD pipelines.',
    readinessScore: 81,
    employabilityScore: 85,
    technicalScore: 84,
    softSkillScore: 82,
    createdAt: '2025-10-05T09:00:00Z',
    updatedAt: '2026-08-28T11:00:00Z',
    skills: [
      { skillId: 'sk_aws', skillName: 'AWS Cloud', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'certification_verified', score: 88 },
      { skillId: 'sk_docker', skillName: 'Docker', category: 'technical', proficiencyLevel: 'advanced', verificationLevel: 'project_verified', score: 85 },
      { skillId: 'sk_k8s', skillName: 'Kubernetes', category: 'technical', proficiencyLevel: 'intermediate', verificationLevel: 'assessment_verified', score: 76 },
      { skillId: 'sk_python', skillName: 'Python', category: 'technical', proficiencyLevel: 'intermediate', verificationLevel: 'assessment_verified', score: 80 },
    ],
    projects: [
      {
        id: 'proj_4',
        title: 'AutoOps GitOps CI/CD Controller',
        description: 'Automated Kubernetes deployments with GitHub Actions and Terraform infrastructure state management.',
        role: 'DevOps Lead',
        techStack: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'GitHub Actions'],
        verified: true,
      },
    ],
    certifications: [
      {
        id: 'cert_4',
        title: 'AWS Certified Solutions Architect – Associate',
        issuingOrganization: 'Amazon Web Services',
        issueDate: '2025-09-01',
        skillsCovered: ['AWS Cloud', 'Architecture', 'Security', 'VPC'],
        verified: true,
      },
    ],
    internships: [],
  },
];

export const DEMO_INDUSTRIES: IndustryProfile[] = [
  {
    uid: 'ind_techcorp',
    email: 'careers@techcorp.in',
    name: 'TechCorp India',
    role: 'industry',
    institutionId: 'inst_iitb',
    companyName: 'TechCorp India Pvt Ltd',
    industrySector: 'Enterprise Software & Cloud Systems',
    website: 'https://techcorp.in',
    companySize: '1,000 - 5,000 employees',
    headquarters: 'Bengaluru, Karnataka',
    description: 'Leading provider of enterprise SaaS solutions, cloud infrastructure, and AI-driven automation tools across APAC.',
    verified: true,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    uid: 'ind_innovateai',
    email: 'recruitment@innovateai.com',
    name: 'Innovate AI Labs',
    role: 'industry',
    institutionId: 'inst_nitt',
    companyName: 'Innovate AI Labs',
    industrySector: 'Artificial Intelligence & Generative AI',
    website: 'https://innovateai.com',
    companySize: '250 - 500 employees',
    headquarters: 'Hyderabad, Telangana',
    description: 'Cutting-edge AI research studio specializing in GenAI agents, RAG engines, and computer vision for healthcare.',
    verified: true,
    createdAt: '2024-06-10T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    uid: 'ind_cloudscale',
    email: 'hr@cloudscale.io',
    name: 'CloudScale Solutions',
    role: 'industry',
    institutionId: 'inst_bits',
    companyName: 'CloudScale Solutions',
    industrySector: 'Cloud Consulting & DevOps',
    website: 'https://cloudscale.io',
    companySize: '500 - 1,000 employees',
    headquarters: 'Pune, Maharashtra',
    description: 'Specialists in multi-cloud transformation, Kubernetes modernization, and 24/7 SRE managed services.',
    verified: true,
    createdAt: '2024-03-20T00:00:00Z',
    updatedAt: '2026-07-20T00:00:00Z',
  },
];

export const DEMO_ACADEMICIANS: AcademicianProfile[] = [
  {
    uid: 'acad_raman',
    email: 'ksraman@iitb.ac.in',
    name: 'Dr. K. S. Raman',
    role: 'academician',
    institutionId: 'inst_iitb',
    institutionName: 'IIT Bombay',
    department: 'Computer Science & Engineering',
    designation: 'Senior Professor & HOD',
    expertise: ['Distributed Systems', 'Cloud Computing', 'Database Management'],
    researchAreas: ['Scalable Microservices', 'Consensus Algorithms'],
    consultancyAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    uid: 'acad_meera',
    email: 'meera.s@nitt.edu',
    name: 'Prof. Meera Swaminathan',
    role: 'academician',
    institutionId: 'inst_nitt',
    institutionName: 'NIT Trichy',
    department: 'Data Science & AI',
    designation: 'Associate Professor',
    expertise: ['Natural Language Processing', 'Deep Learning', 'Computer Vision'],
    researchAreas: ['RAG Architectures', 'Multimodal LLMs'],
    consultancyAvailable: true,
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2026-08-10T00:00:00Z',
  },
];

export const DEMO_ADMINS: InstitutionAdminProfile[] = [
  {
    uid: 'admin_deshmukh',
    email: 'placement.cell@iitb.ac.in',
    name: 'Prof. R. V. Deshmukh',
    role: 'institution_admin',
    institutionId: 'inst_iitb',
    institutionName: 'IIT Bombay',
    code: 'IITB',
    location: 'Mumbai, Maharashtra',
    website: 'https://www.iitb.ac.in',
    totalStudents: 12500,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const DEMO_JOBS: JobOpportunity[] = [
  {
    id: 'job_1',
    industryId: 'ind_techcorp',
    companyName: 'TechCorp India',
    title: 'Full Stack Software Engineer',
    type: 'job',
    description: 'We are looking for a high-energy Full Stack Engineer proficient in Next.js, React, Node.js, and SQL to build responsive web portals for global enterprise clients.',
    location: 'Bengaluru, KA (Hybrid)',
    workMode: 'hybrid',
    experienceLevel: '0-2 Years (Freshers / 2026 Batch)',
    salaryOrStipend: '₹14 - 18 LPA',
    requiredSkills: ['JavaScript', 'React', 'Next.js', 'Node.js', 'SQL'],
    preferredSkills: ['TypeScript', 'Docker', 'AWS Cloud'],
    degreeRequired: 'B.Tech / M.Tech in CS/IT/ECE',
    graduationYearEligible: [2025, 2026],
    deadline: '2026-10-31',
    createdAt: '2026-08-20T00:00:00Z',
    institutionId: 'inst_iitb',
  },
  {
    id: 'job_2',
    industryId: 'ind_innovateai',
    companyName: 'Innovate AI Labs',
    title: 'AI / GenAI Research Associate',
    type: 'job',
    description: 'Join our research team to build cutting-edge RAG engines, vector database pipelines, and agentic workflows using Python, PyTorch, Pinecone, and Gemini API.',
    location: 'Hyderabad, TS (On-Site)',
    workMode: 'on_site',
    experienceLevel: '0-1 Years',
    salaryOrStipend: '₹18 - 24 LPA',
    requiredSkills: ['Python', 'Machine Learning', 'Deep Learning', 'NLP & LLMs', 'SQL'],
    preferredSkills: ['Pinecone', 'LangChain', 'Docker'],
    degreeRequired: 'B.Tech / M.Tech in AI/DS/CS',
    graduationYearEligible: [2025, 2026],
    deadline: '2026-11-15',
    createdAt: '2026-08-25T00:00:00Z',
    institutionId: 'inst_nitt',
  },
  {
    id: 'job_3',
    industryId: 'ind_cloudscale',
    companyName: 'CloudScale Solutions',
    title: 'Associate Cloud & DevOps Engineer',
    type: 'job',
    description: 'Responsible for infrastructure as code, Kubernetes deployment automation, and AWS cloud security hardening.',
    location: 'Remote',
    workMode: 'remote',
    experienceLevel: '0-2 Years',
    salaryOrStipend: '₹12 - 16 LPA',
    requiredSkills: ['AWS Cloud', 'Docker', 'Kubernetes', 'Python', 'Git & GitHub'],
    preferredSkills: ['System Design', 'Cybersecurity'],
    degreeRequired: 'B.Tech / B.E. in CS/ECE/EEE',
    graduationYearEligible: [2025, 2026],
    deadline: '2026-10-15',
    createdAt: '2026-08-10T00:00:00Z',
  },
];

export const DEMO_INTERNSHIPS: JobOpportunity[] = [
  {
    id: 'int_1',
    industryId: 'ind_techcorp',
    companyName: 'TechCorp India',
    title: 'Frontend Development Intern (React / Next.js)',
    type: 'internship',
    description: '6-month stipend internship focusing on building rich UI components, Tailwind styling, and API integrations for enterprise analytics dashboards.',
    location: 'Bengaluru / Remote',
    workMode: 'hybrid',
    experienceLevel: 'Students (Pre-final / Final Year)',
    salaryOrStipend: '₹45,000 / month',
    duration: '6 Months (Jan 2027 - Jun 2027)',
    requiredSkills: ['JavaScript', 'React', 'TypeScript', 'Communication'],
    preferredSkills: ['Next.js', 'Tailwind CSS', 'Git & GitHub'],
    degreeRequired: 'B.Tech / B.E. / MCA',
    graduationYearEligible: [2026, 2027],
    deadline: '2026-10-30',
    createdAt: '2026-08-28T00:00:00Z',
    institutionId: 'inst_iitb',
  },
  {
    id: 'int_2',
    industryId: 'ind_innovateai',
    companyName: 'Innovate AI Labs',
    title: 'RAG & Data Science Intern',
    type: 'internship',
    description: 'Hands-on role building data ingestion pipelines, vector indexing with Pinecone, and evaluation benchmarks for LLM apps.',
    location: 'Hyderabad, TS',
    workMode: 'on_site',
    experienceLevel: 'Students',
    salaryOrStipend: '₹55,000 / month',
    duration: '6 Months',
    requiredSkills: ['Python', 'Machine Learning', 'NLP & LLMs', 'SQL'],
    preferredSkills: ['Problem Solving', 'Git & GitHub'],
    degreeRequired: 'B.Tech / M.Tech',
    graduationYearEligible: [2026, 2027],
    deadline: '2026-11-01',
    createdAt: '2026-08-30T00:00:00Z',
    institutionId: 'inst_nitt',
  },
];

export const DEMO_APPLICATIONS: JobApplication[] = [
  {
    id: 'app_1',
    jobId: 'job_1',
    jobTitle: 'Full Stack Software Engineer',
    companyName: 'TechCorp India',
    studentId: 'std_aarav',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@iitb.ac.in',
    institutionId: 'inst_iitb',
    institutionName: 'IIT Bombay',
    appliedAt: '2026-08-22T14:30:00Z',
    status: 'shortlisted',
    matchScore: 89,
    aiMatchExplanation: 'Aarav matches 90% of required technical skills (React, Next.js, Node.js, JavaScript, SQL) and holds relevant Meta Front-End Certification.',
    resumeUrl: 'https://storage.googleapis.com/skillbridge-demo/resumes/aarav_sharma_resume.pdf',
  },
  {
    id: 'app_2',
    jobId: 'int_1',
    jobTitle: 'Frontend Development Intern (React / Next.js)',
    companyName: 'TechCorp India',
    studentId: 'std_aarav',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@iitb.ac.in',
    institutionId: 'inst_iitb',
    institutionName: 'IIT Bombay',
    appliedAt: '2026-08-29T10:15:00Z',
    status: 'interview_scheduled',
    matchScore: 94,
    aiMatchExplanation: 'Exceptional match for Frontend Intern role. Has verified Next.js projects and strong assessment scores.',
    resumeUrl: 'https://storage.googleapis.com/skillbridge-demo/resumes/aarav_sharma_resume.pdf',
  },
];

export const DEMO_RAG_DOCUMENTS: RAGDocument[] = [
  {
    documentId: 'doc_placement_policy_iitb',
    institutionId: 'inst_iitb',
    userId: 'admin_deshmukh',
    documentType: 'placement_policy',
    title: 'IIT Bombay Official Placement & Internship Guidelines 2026-2027',
    source: 'Placement Cell Handbook',
    permissions: 'institution_only',
    contentChunkCount: 12,
    uploadedAt: '2026-07-01T00:00:00Z',
  },
  {
    documentId: 'doc_fullstack_career_roadmap',
    institutionId: 'inst_iitb',
    userId: 'admin_deshmukh',
    documentType: 'career_guide',
    title: 'Industry Skill Expectations: Full Stack & Cloud Developer 2026',
    source: 'TechCorp & CloudScale Joint Report',
    permissions: 'public',
    contentChunkCount: 8,
    uploadedAt: '2026-08-10T00:00:00Z',
  },
  {
    documentId: 'doc_aiml_interview_guide',
    institutionId: 'inst_nitt',
    userId: 'acad_meera',
    documentType: 'interview_prep',
    title: 'Mastering AI/ML & RAG Architecture Interviews',
    source: 'Innovate AI Labs Research Paper',
    permissions: 'public',
    contentChunkCount: 15,
    uploadedAt: '2026-08-12T00:00:00Z',
  },
];
